### ISSUE TITLE
Redirect https://www.cncf.ci/ to https://cncf.ci/

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#140]
Request: Redirect https://www.cncf.ci/ to https://cncf.ci/
---

### Short description: 
- What I see now: 
  - when I type in https://www.cncf.ci/, I can see an error  "This site can’t be reached www.cncf.ci’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN"
- What I'd like to see: 
   - when I type in https://www.cncf.ci/, I am redirected to https://cncf.ci/ and I can see the content on the CNCF CI Status Dashboard

### Tasks: 

- [x]   add redirect from https://www.cncf.ci/ to https://cncf.ci/

**Comment by taylor** [comment]
@hh, can you assist with this please.  I think you still have admin access to that domain and the records at dnsimple.

**Comment by hh** [comment]
Done.

![image](https://user-images.githubusercontent.com/31331/55089797-dec19300-5112-11e9-9637-abd435fe4cf4.png)

**Comment by dankohn** [comment]
Not quite. http://www.cncf.ci correctly redirects to https://cncf.ci but https://www.cncf.ci does not redirect to https://cncf.ci.

**Comment by hh** [comment]
DNSimple doesn't directly support https:// => redirects.

The straightforward approach is to point www.cncf.ci to an IP that has an ingress using https://github.com/jetstack/cert-manager.

- https://support.dnsimple.com/articles/redirector-https/
- https://blog.dnsimple.com/2016/08/https-redirects/

**Comment by taylor** [comment]
Thanks for adding DNS access @hh.  We'll setup the redirects and DNS records.

**Comment by denverwilliams** [comment]
Redirects for www are now enabled.

We are already using ingress for https://cncf.ci so the quick fix was to add an Nginx redirect for www.
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://cncf.ci"
  name: www-to-fnt-production
spec:
  tls:
  - secretName: www-to-fnt-production-tls
    hosts:
    - www.cncf.ci
  rules:
    - host: www.cncf.ci
      http:
        paths:
          - backend:
              serviceName: nginx-production-nginx-ingress-default-backend
              servicePort: 80
            path: /
```
