### ISSUE TITLE
[Upstream] CoreDNS builds failing on cncf.ci 

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#18]
Job #53591 triggered about 15 hours ago

https://gitlab.cncf.ci/coredns/coredns/-/jobs/53591

Error: `core/dnsserver/register.go:33:13: cannot use newContext (type func() caddy.Context) as type func(*caddy.Instance) caddy.Context in field value`

---

Seems to be resolved by https://github.com/coredns/coredns/commit/22409290d9ded3b726ad9d8d2534700fc96e2522

---

Next scheduled refresh of cncf.ci in the morning

**Comment by lixuna** [comment]
CoreDNS 1.0.5 still showing RED

Opened new ticket #22 up update version to 1.0.6

**Comment by lixuna** [comment]
Potential issue: 

We are using the https://github.com/coredns/coredns/blob/master/Makefile.release which may not be up-to-date. 

It appears that the https://github.com/coredns/coredns/blob/master/Makefile has been updated 4 days ago.

**Comment by lixuna** [comment]
cc @fturib

**Comment by lixuna** [comment]
Related: https://github.com/coredns/coredns/issues/1567

**Comment by fturib** [comment]
In the job failing output, I have these lines:

```
$ ln -s /builds /go/src/github.com
$ cd /go/src/github.com/coredns/coredns
$ go get github.com/estesp/manifest-tool
$ go get github.com/progrium/gh-release
$ go get github.com/mholt/caddy
$ go get github.com/miekg/dns
$ go get golang.org/x/net/context
$ go get golang.org/x/text
$ go get github.com/coredns/forward
$ go get github.com/prometheus/client_golang/prometheus/promhttp
$ go  get -u github.com/prometheus/client_golang/prometheus
$ make -j $(getconf _NPROCESSORS_ONLN) -f Makefile.release build DOCKER=null
```

But in the coredns-configuration we are not using the same ... 
`https://github.com/crosscloudci/coredns-configuration/blob/master/.gitlab-ci.yml`

we have:

```
compile:
  image: crosscloudci/debian-go
  stage: build
  script:
    - ln -s /builds /go/src/github.com
    - make -j $(getconf _NPROCESSORS_ONLN) all
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 5 weeks
    paths:
      - ./coredns
```

so where is defined the code with Makefile.release ?
and my question is : all these 'go get' that happen before the Makefile are encoded somewhere or are thy coming from the Makefile of coredns ?
